### ISSUE TITLE
Import-OVResources.ps1: ProfileTemplate w/o BIOS settings

### ISSUE THREAD

**Issue by aricbernard** [DungKHoang/Import-Export-OneView-Resources#2]
When executing the Import-OVResources.ps1, if the Server Profile Template has no managed BIOS settings the following errors will be thrown:

```
You cannot call a method on a null-valued expression.
At C:\Import-Export-OneView-Resources-main\Import-OVResources.ps1:**6719** char:5

You cannot call a method on a null-valued expression.
At C:\Import-Export-OneView-Resources-main\Import-OVResources.ps1:**7356** char:5
```

My recommendation would be to wrap each of the offending lines in an if statement as follows:
`if ($biosSettings.count){<existing line>}`

**Comment by DungKHoang** [comment]
Thanks for reporting. Fixed!
