### ISSUE TITLE
Import folder

### ISSUE THREAD

**Issue by aricbernard** [DungKHoang/Import-Export-OneView-Resources#3]
Some customers may be working with multiple source or target environments.  When performing an export from each source environment, an export file is created which includes the source environment IP address. (e.g. ExportFrom-10.10.10.10.xlsx).  However, when executing Import-OVResources.ps1, all of the folders created for the output are created in the script root folder and are not stamped with the source environment IP address.

If a customer were to export from 2 different environments and subsequently use Import-OVResources.ps1 against both of the xslx export files, the output would be combined into the same folders potentially leading to a number of issues including importing information from multiple source environments into the inappropriate target environments.

I would suggest creating a single file in the root with a name the same as the xlsx export file (e.g. ExportFrom-10.10.10.10) and then create all of the folders necessary for script output within that folder.

**Comment by DungKHoang** [comment]
I agree. I was thinking about creating subfolders under script to reflect where the export comes from. Something like:
- export-from-10.1.10.2.xlsx and export-from-10.1.10.3.xlsx
- scripts
- ----- 10.1.10.2 folder
- ------10.1.10.3 folder
-This is where all import scripts generated from xlsx file will be

Will take a look on this
